/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AFromItem: typeof import('@arco-design/web-vue')['FromItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ATabePane: typeof import('@arco-design/web-vue')['TabePane']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    CustomUploader: typeof import('./src/components/CustomUploader/index.vue')['default']
    DefaultLayout: typeof import('./src/components/DynamicForm/DefaultLayout.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm/index.vue')['default']
    FormDesign: typeof import('./src/components/FormDesign/index.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Layout1: typeof import('./src/components/Layout1.vue')['default']
    MainSection: typeof import('./src/components/FormDesign/MainSection.vue')['default']
    Material: typeof import('./src/components/FormDesign/Material.vue')['default']
    MaterialSection: typeof import('./src/components/FormDesign/MaterialSection.vue')['default']
    PropsSection: typeof import('./src/components/FormDesign/PropsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/VirtualList/Test.vue')['default']
    VirtualItem: typeof import('./src/components/VirtualList/VirtualItem.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList/index.vue')['default']
    WaterMark: typeof import('./src/components/WaterMark.vue')['default']
  }
}
