/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    CustomCheckbox: typeof import('./src/components/DynamicForm/materials/CustomCheckbox.vue')['default']
    CustomCodeEditor: typeof import('./src/components/DynamicForm/materials/CustomCodeEditor.vue')['default']
    CustomEditor: typeof import('./src/components/DynamicForm/materials/CustomEditor.vue')['default']
    CustomJson: typeof import('./src/components/DynamicForm/materials/CustomJson.vue')['default']
    CustomLayout: typeof import('./src/components/FormDesign/CustomLayout.vue')['default']
    CustomRadio: typeof import('./src/components/DynamicForm/materials/CustomRadio.vue')['default']
    CustomSelect: typeof import('./src/components/DynamicForm/materials/CustomSelect.vue')['default']
    CustomText: typeof import('./src/components/DynamicForm/materials/CustomText.vue')['default']
    CustomUploader: typeof import('./src/components/CustomUploader/index.vue')['default']
    DefaultLayout: typeof import('./src/components/DynamicForm/DefaultLayout.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm/index.vue')['default']
    FormDesign: typeof import('./src/components/FormDesign/index.vue')['default']
    MainSection: typeof import('./src/components/FormDesign/MainSection.vue')['default']
    MainSectionV2: typeof import('./src/components/FormDesign/MainSectionV2.vue')['default']
    MaterialSection: typeof import('./src/components/FormDesign/MaterialSection.vue')['default']
    PropsSection: typeof import('./src/components/FormDesign/PropsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/VirtualList/Test.vue')['default']
    VirtualItem: typeof import('./src/components/VirtualList/VirtualItem.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList/index.vue')['default']
    WaterMark: typeof import('./src/components/WaterMark.vue')['default']
  }
}
